### ISSUE TITLE
TwitchIO Crash

### ISSUE THREAD

**Issue by bowerscd** [bowerscd/ansf#4]
```
/usr/local/lib/python3.11/site-packages/twitchio/http.py:145: RuntimeWarning: coroutine 'RateBucket._wait' was never awaited
await self.bucket
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
+ Exception Group Traceback (most recent call last):
|   File "/app/__main__.py", line 87, in <module>
|     __main()
|   File "/app/__main__.py", line 84, in __main
|     asyncio.run(__bot_main(argv))
|   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
|     return runner.run(main)
|            ^^^^^^^^^^^^^^^^
|   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
|     return self._loop.run_until_complete(task)
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
|     return future.result()
|            ^^^^^^^^^^^^^^^
|   File "/app/__main__.py", line 46, in __bot_main
|     async with asyncio.TaskGroup() as tg:
|   File "/usr/local/lib/python3.11/asyncio/taskgroups.py", line 133, in __aexit__
|     raise me from None
| ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
+-+---------------- 1 ----------------
| Traceback (most recent call last):
|   File "/app/twitch/cogs/turing.py", line 196, in turing_main
|     while len(await self._bot.fetch_streams(user_logins=[channel.name])) == 0:
|               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/usr/local/lib/python3.11/site-packages/twitchio/client.py", line 679, in fetch_streams
|     data = await self._http.get_streams(
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/usr/local/lib/python3.11/site-packages/twitchio/http.py", line 692, in get_streams
|     return await self.request(Route("GET", "streams", query=q, token=token))
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/usr/local/lib/python3.11/site-packages/twitchio/http.py", line 145, in request
|     await self.bucket
| TypeError: __await__() returned a coroutine
+------------------------------------
```

**Comment by bowerscd** [comment]
Based on the crash it looks like a bug in the rate limiting code for twitchio. I should probably adjust the poll for live status to avoid limiting entirely. 

It'll be temporary until I can get a webhook established for pubsub.
